### PR TITLE
Shapecutter example

### PR DESCRIPTION
**Pull request by kaedonkers**
Add shapecutter example from https://github.com/informatics-lab/covid-19_shapecutter

### CODE REVIEW

**Comment by aaronspring** [comment]
I can provide a much leaner implementation of netcdf aggregation over shapefile regions using https://github.com/mathause/regionmask. This would be without the looping and possibility facilitates the automatisation #9. Shall I start a PR? And if so: where is the data stored? The example here runs with locally downloaded data as far as I can see. @kaedonkers @tam203

**Comment by tam203** [comment]
Hi @aaronspring. The data is all available in the blob, [README](https://metdatasa.blob.core.windows.net/covid19-response/README_data.html) and [index] (https://metdatasa.blob.core.windows.net/covid19-response/index.html) will hopefully point you in the right direction. Anything under `global_daily` would be a good example.

In the above example it is running on our platform that we can add you on to if you'd like. On the platform the data is available on an NFS mounted disk. But due demo purposes you should be able to either down load a few file or even use direct from the blob store. There are some examples of this [here](https://github.com/informatics-lab/covid19-ai4earth-examples)

Cheers

**Comment by aaronspring** [comment]
Thoughts about this implementation? regionmask is well tested. 

https://github.com/informatics-lab/covid19-examples-and-docs/pull/16

**Comment by aaronspring** [comment]
https://github.com/aaronspring/covid19-examples-and-docs/blob/AS_shape_regionmask/examples/1.3.0%20Extracting%20Regional%20Data%20using%20Shapefiles%20alternative.ipynb

**Comment by tam203** [comment]
@aaronspring  Hi, looks awesome but unfortunaly I'm getting:

```
'AttributeError: module 'regionmask' has no attribute 'from_geopandas' 
```
What version are you using? I'm `0.5.0`

Screenshot 2020-04-25 at 21 55 24

Cheers.

**Comment by kaedonkers** [comment]
Hi @aaronspring, thanks so much for this example! This is exactly the kind of xarray based solution I thought would be much simpler than what I've done already 😅 

@tam203 I had a look at regionmask and it looks like `from_geopandas` is only a few days old (!) and [unreleased](https://github.com/mathause/regionmask/blob/35da3e463b8f04a7197a8ec059a8aeb37ab990c2/docs/whats_new.rst#v060-unreleased).
@aaronspring When do you think v0.6.0 of regionmask will be released?

**Comment by aaronspring** [comment]
Yes. I implement from_geopandas with the help of @mathause. The is no new release of regionmask yet. For now you need to install it from github source

**Comment by aaronspring** [comment]
Did it work when installing regionmask from source? @kaedonkers @tam203 

I will try to get a cloud version running. My laptop and remote internet connection performance are quite poor for this...

**Comment by mathause** [comment]
You should be able to install `regionmask` master directly with:
```
pip install git+https://github.com/mathause/regionmask.git
```
(Given you already installed all dependenies.) I can make a release if you prefer not to work with a development version, but this may take some days.

**Comment by tam203** [comment]
[image: image.png]

Got a new issue but I've not debugged at all. @kaedonkers
<https://github.com/kaedonkers> if you want to test I've updated the
default environment.
---

.

**Comment by tam203** [comment]
error

**Comment by mathause** [comment]
Ah yes, the error message is missleading (fixed by mathause/regionmask#119). This means that `gdf` has no column named `"name"`, the part about NaturalEarth can be ignored.

What does `display(gdf)` and `gdf.columns` show?

**Comment by aaronspring** [comment]
I also got this problem. didnt solve it yet. this comes from how the shapefiles are read into geopandas. if only .shp file is present it doesnt work, with some of these other files `read_file` works but the columns have weird names. 
locally I just download all these files or often for shapefiles even just a zip file. then it usually works with the expected column names.

working on this tomorrow in https://binder.pangeo.io/v2/gh/aaronspring/covid19-examples-and-docs/AS_pangeo_notebook.

**Pull request merged**
